/**
 * Bundles the screensaver engine into the single self-contained HTML file
 * shipped inside the native macOS screensaver bundle
 * (macos-screensaver/DragStripValley/Resources/screensaver.html).
 *
 * Run with: npm run build:saver
 * The output is committed so building the .saver on a Mac only needs Xcode.
 */

import { buildSync } from "esbuild";
import { writeFileSync } from "fs";
import { join } from "path";
import { APP_VERSION } from "../src/lib/version";

const root = join(__dirname, "..");

const result = buildSync({
  entryPoints: [join(root, "scripts/saver-entry.ts")],
  bundle: true,
  format: "iife",
  minify: true,
  write: false,
  target: ["safari15"],
  legalComments: "none",
});
const js = result.outputFiles[0].text;

const html = `<!DOCTYPE html>
<!-- Generated by scripts/build-saver-html.ts (npm run build:saver) — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Drag Strip Valley</title>
<style>
  html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; background: #5fb0d4; cursor: none; }
  * { user-select: none; -webkit-user-select: none; }
  #scene { position: absolute; inset: 0; width: 100%; height: 100%; }
  .overlay { position: absolute; pointer-events: none; font-family: -apple-system, system-ui, sans-serif; }
  #clock-wrap { bottom: 24px; right: 32px; text-align: right; }
  #clock {
    color: rgba(255,255,255,0.9); font-size: 48px; font-weight: 300; letter-spacing: -0.02em;
    font-variant-numeric: tabular-nums; text-shadow: 0 2px 8px rgba(0,0,0,0.35);
  }
  #date { color: rgba(255,255,255,0.6); font-size: 14px; font-weight: 500; margin-top: 4px; text-shadow: 0 1px 4px rgba(0,0,0,0.4); }
  #brand {
    bottom: 24px; left: 32px; color: rgba(255,255,255,0.5); font-size: 12px; font-weight: 600;
    letter-spacing: 0.1em; text-transform: uppercase; text-shadow: 0 1px 4px rgba(0,0,0,0.4);
  }
</style>
</head>
<body>
<canvas id="scene"></canvas>
<div id="clock-wrap" class="overlay"><div id="clock"></div><div id="date"></div></div>
<div id="brand" class="overlay">Timing Data \u00b7 Drag Strip Valley \u00b7 v${APP_VERSION}</div>
<script>${js}</script>
</body>
</html>
`;

const out = join(root, "macos-screensaver/DragStripValley/Resources/screensaver.html");
writeFileSync(out, html);
console.log(`Wrote ${out} (${(html.length / 1024).toFixed(1)} kB)`);
